### ISSUE TITLE
Assets precompilation fails

### ISSUE THREAD

**Issue by 5ika** [octree-gva/decidim-in-docker#1]
During the assets precompilation (trough the Docker build execution) fails with this following error. Directory `images/` doesn't exist in base code.

```
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '../../images' in '/home/decidim/app/app/packs/src/decidim'
    at /home/decidim/app/node_modules/webpack/lib/Compilation.js:2011:28
    at /home/decidim/app/node_modules/webpack/lib/ContextModuleFactory.js:210:15
    at /home/decidim/app/node_modules/neo-async/async.js:2830:7
    at /home/decidim/app/node_modules/neo-async/async.js:6877:13
    at /home/decidim/app/node_modules/webpack/lib/ContextModuleFactory.js:180:26
    at finishWithoutResolve (/home/decidim/app/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /home/decidim/app/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /home/decidim/app/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/home/decidim/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/decidim/app/node_modules/enhanced-resolve/lib/Resolver.js:410:5
resolve '../../images' in '/home/decidim/app/app/packs/src/decidim'
  using description file: /home/decidim/app/package.json (relative path: ./app/packs/src/decidim)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/decidim/app/package.json (relative path: ./app/packs/images)
      /home/decidim/app/app/packs/images doesn't exist
```

**Comment by froger** [comment]
@5ika thanks for testing this. I could reproduce and fix.
If you can test again, that would be cool. I've updated the readme about a credential step that will forbid the app to run.
